inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - '**/snapshots/**/*'

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false
