name: CI

on:
  - pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          cache: npm

      - name: Prettier
        run: npx prettier --check .

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Set up Ruby
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Set up Ruby
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: RSpec
        run: bundle exec rspec
